### ISSUE TITLE
No sass no bootstrap 

### ISSUE THREAD

**Issue by gagarine** [interface-network/interface-network.com#2]
We don’t need sass (modern CSS does it all) neither bootstrap. Let’s keep it simple and modern. No JS. No cookie.

**Comment by hypnoseal** [comment]
My arguments for Bootstrap:

- Vastly reduces dev time
- Ensures cross-browser consistency
- Cross-device responsive design already accomplished

**Comment by gagarine** [comment]
I want to emancipated myself from bootstrap. The tools is still making sense for prototyping app. But less today for a 4 pages website.
